# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exerciseName',
            new_name='exercise_name',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workoutName',
            new_name='workout_name',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workoutType',
            new_name='workout_type',
        ),
    ]
